// Generated by tools/generate.py; edit data/model.json.
#ifndef GREEN_STRIPE_MODEL_CONSTANTS_HPP
#define GREEN_STRIPE_MODEL_CONSTANTS_HPP
namespace greenstripe { namespace model {
static const unsigned oversampling = 4;
static const unsigned default_oversampling = 0;
static const unsigned latency_2x_frames = 3;
static const unsigned nominal_latency_frames = 4;
static const double reference_peak_dbfs = -21;
static const double qbias_db = 1;
static const double attack_slow_seconds = 0.00080000000000000004;
static const double attack_fast_seconds = 2.0000000000000002e-05;
static const double release_slow_seconds = 1.1000000000000001;
static const double release_fast_seconds = 0.050000000000000003;
static const double input_highpass_hz = 8;
static const double output_highpass_hz = 5;
static const double amplifier_lowpass_hz = 45000;
static const double ratios[] = {2, 4, 8, 12, 20, 16};
static const double thresholds_dbfs[] = {-25, -24, -21, -19.5, -18, -22};
static const double knees_db[] = {7.5, 6, 4, 3, 2, 1.5};
static const double halfband_stage1[] = {0.04063346092419326, 0.1505051290226746, 0.30075705599187408, 0.46077450496145061, 0.6095243148961883, 0.73850384111885725, 0.84922381039206607, 0.9497427837050002};
static const double halfband_stage2[] = {0.040341222658423818, 0.16379193172022141, 0.38282159255650028, 0.73875012537359719};
} }
#endif
