#!/usr/bin/env python3
"""Reproduzierbare ngspice-Messung der lokalen, unveränderten GC-Koeffizienten.

Abhängigkeit: Python >= 3.9, NumPy, ngspice (hier 45.2).
Die DDT-Übersetzung verändert keine Netzwerkgleichung; siehe BERICHT.md.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor
import csv
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import time

import numpy as np


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCE = ROOT / "docs/sauce/xformer.lib"
FREQUENCIES = (20, 100, 1000, 10000, 20000)
LEVELS = tuple(range(-30, 7, 3))
RATE = 48000
MODELS = {
    "GCOT-SE-01": {"stage": "60s", "topology": "se", "inner": "xc"},
    "GCOT-PP-03": {"stage": "80s", "topology": "pp", "inner": "xc"},
    "GCOT-PP-04": {"stage": "00s", "topology": "pp", "inner": "xc"},
    "GCSYMETRICAL": {"stage": "Symmetric", "topology": "pp", "inner": "xgc"},
}


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_text(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(text)


def write_json(path, value):
    write_text(path, json.dumps(value, indent=2, ensure_ascii=False, allow_nan=False) + "\n")


def read_csv(path):
    return list(csv.DictReader(line for line in path.read_text(encoding="utf-8").splitlines()
                               if not line.startswith("#")))


def write_csv(path, rows, comments=()):
    with path.open("w", encoding="utf-8", newline="") as stream:
        for comment in comments:
            stream.write("# " + comment + "\n")
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def adapt_model():
    original = SOURCE.read_text(encoding="utf-8")
    adapted = original
    for sensor, node, turns in (("Vp", "ddt_p", "Np"),
                                ("Vp1", "ddt_p1", "Np2"),
                                ("Vp2", "ddt_p2", "Np2")):
        pattern = r"(?m)^(\s*B\w+\s+\S+\s+\S+\s+V\s*=\s*)\{" + turns + \
                  r"\}\s*\*\s*DDT\(I\(" + sensor + r"\)\)\s*$"
        replacement = (f"  * Exact realization: I(L) = I({sensor}), V(L) = {turns}*dI/dt.\n"
                       f"  F{node} 0 {node} {sensor} 1\n"
                       f"  L{node} {node} 0 {{{turns}}}\n"
                       rf"\g<1>V({node})")
        adapted, count = re.subn(pattern, replacement, adapted)
        if count != 1:
            raise ValueError(f"Expected exactly one DDT source for {sensor}, found {count}")
    # Only correct mismatched END labels; no element, pin or parameter is changed.
    for old, new in (("GOT-SE-01", "GCOT-SE-01"), ("GOT-PP-03", "GCOT-PP-03"),
                     ("GOT-PP-04", "GCOT-PP-04"), ("SYMETRICAL", "GCSYMETRICAL")):
        adapted = adapted.replace(".ENDS " + old, ".ENDS " + new)
    header = ("* Generated by run_simulations.py from ../sauce/xformer.lib.\n"
              f"* Original SHA256: {sha256(SOURCE)}\n"
              "* Only DDT realization and four .ENDS labels differ.\n"
              "* Auxiliary inductors implement derivatives, NOT physical winding inductances.\n")
    write_text(HERE / "xformer-ddt.inc", header + adapted)
    parameters = {}
    for name in MODELS:
        block = re.search(r"\.SUBCKT " + name + r"\b(.*?)\.ENDS", original, re.S).group(1)
        parameters[name] = {key: float(value) for key, value in
                            re.findall(r"\b(C|a|n|R|b|m|Np|Ns)\s*=\s*([\deE.+-]+)", block)}
        if len(parameters[name]) != 8:
            raise ValueError("Incomplete original parameters for " + name)
    # Exact KCL reduction avoids a numerically ill-conditioned derivative loop.
    # u = voltage across the ORIGINAL Cc; w = -I(Vp) (left half), +I(Vp2) (right).
    # C*du/dt = j+w; Nhalf*dw/dt = u; j = q/R+b*abs(q)^m*sgn(q).
    # No pole, sign, parameter or loss branch is "repaired" here.
    state = """* KCL-equivalent realization of ../sauce/xformer.lib, not a repaired transformer.
* Generated by run_simulations.py. Original parameters below are copied verbatim.
* State u is original Cc VOLTAGE, not an identified magnetic flux in Wb.
* Cw=Nhalf implements dw/dt=u/Nhalf, including the original positive feedback.
.subckt GC_STATE p ref current_out params: C=1e-3 a=1 n=2 R=1 b=1 m=1 Nh=100
Vsense p ps 0
Bsat ps q V={a}*abs(v(u))**{n}*sgn(v(u))
Rloss q ref {R}
Bloss q ref I={b}*abs(v(q,ref))**{m}*sgn(v(q,ref))
Cu u 0 {C}
Bdu 0 u I=i(Vsense)+v(w)
Cw w 0 {Nh}
Bdw 0 w I=v(u)
Bout current_out 0 V=i(Vsense)+v(w)
.ends GC_STATE

.subckt SingleEnded p1 p2 s1 s2 params: C=1e-3 a=1 n=2 R=1 b=1 m=1 Np=100 Ns=50
Xcore1 p1 p2 current1 GC_STATE C={C} a={a} n={n} R={R} b={b} m={m} Nh={Np}
Bs s1 s2 V={Ns}*v(current1)
.ends SingleEnded

.subckt PushPull p1 ct p2 s1 s2 params: C=1e-3 a=1 n=2 R=1 b=1 m=1 Np=100 Ns=50
Xcore1 p1 ct current1 GC_STATE C={C} a={a} n={n} R={R} b={b} m={m} Nh={Np/2}
Xcore2 p2 ct current2 GC_STATE C={C} a={a} n={n} R={R} b={b} m={m} Nh={Np/2}
Bs s1 s2 V={Ns}*(v(current1)-v(current2))/2
.ends PushPull

"""
    for name in MODELS:
        original_block = re.search(r"(?m)^\.SUBCKT " + name + r"\b.*?^\.ENDS[^\n]*",
                                   original, re.S | re.M).group(0)
        original_block = re.sub(r"(?m)^\.ENDS[^\n]*", ".ENDS " + name, original_block)
        state += original_block + "\n\n"
    write_text(HERE / "xformer-ngspice.inc", f"* Original SHA256: {sha256(SOURCE)}\n" + state)
    return parameters


def make_case(model, freq, level, tag="main", rs=200, load=8,
              start=None, cycles=10, refinement=1, common_mode=False,
              method="trap", initial_u=None, zero_input=False):
    start = max(0.04, 20.0 / freq) if start is None else start
    maxstep = min(1.0 / RATE, 1.0 / (256 * freq)) / refinement
    level_tag = ("m" if level < 0 else "p") + f"{abs(level):g}"
    name = f"{model}__{tag}__f{freq:g}__{level_tag}dBV"
    return dict(model=model, frequency_hz=freq, level_dbv=level, tag=tag,
                case_id=name, source_resistance_ohm=rs, load_ohm=load,
                start_s=start, stop_s=start + cycles / freq,
                max_step_s=maxstep, refinement=refinement, common_mode=common_mode,
                method=method, initial_u=initial_u, zero_input=zero_input)


def circuit(case, include="xformer-ngspice.inc", ac=True, transient=True,
            realization="state"):
    model = case["model"]
    config = MODELS[model]
    pp = config["topology"] == "pp"
    name = case["case_id"]
    base = "xdut." + config["inner"]
    pp_phase = 0 if case["common_mode"] else 180
    lines = [f"Green Stripe 76 - {name}",
             f"* {config['stage']}; {config['topology']}; 48 kHz export, adaptive analog solver.",
             "* dBV refers to open-circuit DIFFERENTIAL source RMS (zero DC).",
             "* Source/loads are explicit test conditions, not original characterization data.",
             f'.include "{include}"',
             f".param FREQ={case['frequency_hz']:.17g} LEVEL_DBV={case['level_dbv']:.17g}",
             f".param RS={case['source_resistance_ohm']:.17g} RL={case['load_ohm']:.17g}",
             ".param AMP=0" if case["zero_input"] else
             ".param AMP={sqrt(2)*10**(LEVEL_DBV/20)}"]
    if pp:
        lines += ["Vplus srcp 0 DC 0 AC 0.5 SIN(0 {AMP/2} {FREQ})",
                  f"Vminus srcn 0 DC 0 AC 0.5 {pp_phase} SIN(0 {{AMP/2}} {{FREQ}} 0 0 {pp_phase})",
                  "Rplus srcp p1 {RS/2}", "Rminus srcn p2 {RS/2}",
                  f"Xdut p1 0 p2 out 0 {model}"]
        source, primary = "v(srcp,srcn)", "v(p1,p2)"
        if case["common_mode"]:
            source, primary = "v(srcp)", "v(p1)"
        vphi = [f"v({base}.c1,{base}.c3)", f"v({base}.c2,{base}.c4)"]
        current = "-i(vplus)"
    else:
        lines += ["Vplus srcp 0 DC 0 AC 1 SIN(0 {AMP} {FREQ})",
                  "Rplus srcp p1 {RS}", f"Xdut p1 0 out 0 {model}"]
        source, primary = "v(srcp)", "v(p1)"
        vphi, current = [f"v({base}.c1,{base}.c2)", "0*v(out)"], "-i(vplus)"
    if realization == "state":
        vphi = [f"v({base}.xcore1.u)", f"v({base}.xcore2.u)" if pp else "0*v(out)"]
    tolerance = 1e-7 / case["refinement"]
    if case["initial_u"] is not None:
        lines += [f".ic v({base}.xcore1.u)={case['initial_u']:.17g}"]
        if pp:
            lines += [f".ic v({base}.xcore2.u)={-case['initial_u']:.17g}"]
    lines += ["Rload out 0 {RL}",
              f".options reltol={tolerance:.12g} abstol=1e-14 vntol=1e-12 method={case['method']}",
              ".control", "set noaskquit", "set numdgt=16", "set wr_vecnames",
              "set wr_singlescale"]
    if ac:
        lines += ["ac dec 200 20 20k", f"let source_v = {source}",
                  f"let primary_v = {primary}",
                  f"wrdata {name}-ac.txt source_v primary_v v(out)"]
    if transient:
        lines += [f"tran {1.0 / RATE:.17g} {case['stop_s']:.17g} "
                  f"{case['start_s']:.17g} {case['max_step_s']:.17g}" +
                  (" uic" if case["initial_u"] is not None else ""),
                  f"let source_v = {source}", f"let primary_v = {primary}",
                  f"let cap1_v = {vphi[0]}", f"let cap2_v = {vphi[1]}",
                  f"let primary_i = {current}",
                  f"wrdata {name}-transient.txt source_v primary_v v(out) cap1_v cap2_v primary_i"]
    return "\n".join(lines + ["quit", ".endc", ".end", ""])


def run_ngspice(executable, case, realization="state", timeout=120):
    name = case["case_id"]
    literal = realization == "literal"
    include = ("../../sauce/xformer.lib" if literal else
               "../xformer-ddt.inc" if realization == "ddt" else "../xformer-ngspice.inc")
    deck = circuit(case, include=include, ac=True, realization=realization)
    deck_path = HERE / "netlists" / (name + ".cir")
    write_text(deck_path, deck)
    start = time.monotonic()
    with tempfile.TemporaryDirectory(prefix="gs76-spice-", dir="/tmp/opencode") as temporary:
        work = Path(temporary)
        model_file = (SOURCE if literal else HERE /
                      ("xformer-ddt.inc" if realization == "ddt" else "xformer-ngspice.inc"))
        # Executed copy changes only the .include path; canonical decks remain portable.
        executed = deck.replace(f'.include "{include}"', f'.include "{model_file}"')
        write_text(work / "run.cir", executed)
        timed_out = False
        try:
            result = subprocess.run([executable, "-n", "-b", "-o", "ngspice.log", "run.cir"],
                                    cwd=work, capture_output=True, text=True, timeout=timeout)
            returncode = result.returncode
        except subprocess.TimeoutExpired:
            timed_out, returncode = True, -1
        log = (work / "ngspice.log").read_text(encoding="utf-8", errors="replace")
        if timed_out:
            log += f"\nRunner: timeout after {timeout} seconds; no accepted transient.\n"
        write_text(HERE / "logs" / (name + ".log"), log)
        arrays = {}
        for key in ("ac", "transient"):
            path = work / (name + "-" + key + ".txt")
            if path.exists():
                arrays[key] = np.loadtxt(path, skiprows=1, ndmin=2)
        error = timed_out or bool(re.search(r"(?i)\baborted\b|timestep too small|^error", log, re.M))
        if realization == "state" and (returncode != 0 or error):
            raise RuntimeError(f"ngspice failed: {name}; see logs/{name}.log")
        if realization == "state":
            data = arrays.get("transient")
            if data is None or not np.all(np.isfinite(data)) or \
                    abs(data[-1, 0] - case["stop_s"]) > 1e-9:
                raise RuntimeError("Missing/incomplete/nonfinite transient: " + name)
        return case, arrays, dict(returncode=returncode, aborted=error,
                                 elapsed_s=time.monotonic() - start,
                                 netlist_sha256=sha256(deck_path))


def fit_harmonics(data, frequency):
    """Time-weighted harmonic regression, with separate slow DC/drift terms.

    Native adaptive times resolve H3/H5 also above the 48-kHz Nyquist frequency.
    The linear/quadratic drift terms are reported, never interpreted as harmonics.
    """
    t = data[:, 0]
    span = t[-1] - t[0]
    u = (t - (t[-1] + t[0]) * 0.5) / span
    design = [np.ones(len(t)), u, u * u]
    for harmonic in range(1, 10):
        angle = 2 * np.pi * frequency * harmonic * t
        design.extend((np.cos(angle), np.sin(angle)))
    matrix = np.array(design).T
    weights = np.empty(len(t))
    weights[0] = (t[1] - t[0]) * 0.5
    weights[-1] = (t[-1] - t[-2]) * 0.5
    weights[1:-1] = (t[2:] - t[:-2]) * 0.5
    root_weight = np.sqrt(weights)
    coefficients = np.linalg.lstsq(matrix * root_weight[:, None],
                                   data[:, 1:] * root_weight[:, None], rcond=None)[0]
    residual = data[:, 1:] - matrix @ coefficients
    rms_residual = np.sqrt(np.sum(weights[:, None] * residual**2, axis=0) / np.sum(weights))
    harmonics = coefficients[3::2] - 1j * coefficients[4::2]
    return coefficients, harmonics, rms_residual


def db(value):
    return 20.0 * math.log10(max(float(abs(value)), 1e-300))


def phase(value):
    return float(np.angle(value, deg=True))


def archive_waveforms(case, data, sampled):
    """Keep original samples in first/last measured cycles, with explicit gaps.

    All ten cycles are used for measurements. Full data can be regenerated with
    the case netlist. Hashes in the manifest identify the full native arrays.
    """
    period = 1.0 / case["frequency_hz"]
    def ends(array):
        selected = ((array[:, 0] <= case["start_s"] + period) |
                    (array[:, 0] >= case["stop_s"] - period))
        return array[selected]
    return {case["case_id"] + "__native": ends(data),
            case["case_id"] + "__48k": ends(sampled)}


def analyze(case, arrays, ac_reference):
    data = arrays["transient"]
    # Avoid imputed TSTART boundaries in regression; all fitted samples are
    # actual ngspice solver output, with time weights for nonuniform steps.
    coeff, harmonics, residual = fit_harmonics(data, case["frequency_hz"])
    fundamental = harmonics[0]
    transfer = fundamental[2] / fundamental[0]
    port_transfer = fundamental[2] / fundamental[1]
    split = (case["start_s"] + case["stop_s"]) * 0.5
    early = fit_harmonics(data[data[:, 0] <= split], case["frequency_hz"])[1][0]
    late = fit_harmonics(data[data[:, 0] >= split], case["frequency_hz"])[1][0]
    duration = data[-1, 0] - data[0, 0]
    averages = np.sum(0.5 * (data[1:, 1:] + data[:-1, 1:]) *
                      np.diff(data[:, 0])[:, None], axis=0) / duration
    ref_freq, ref_h, ref_port = ac_reference
    ref_gain = np.interp(math.log(case["frequency_hz"]), np.log(ref_freq), np.abs(ref_h))
    ref_port_gain = np.interp(math.log(case["frequency_hz"]), np.log(ref_freq), np.abs(ref_port))
    h3 = db(harmonics[2, 2] / fundamental[2])
    h5 = db(harmonics[4, 2] / fundamental[2])
    result = dict(case_id=case["case_id"], model=case["model"], stage=MODELS[case["model"]]["stage"],
                  netlist="netlists/" + case["case_id"] + ".cir",
                  log="logs/" + case["case_id"] + ".log",
                  waveform_archive=case["model"] + "-waveforms.npz",
                  waveform_key=case["case_id"],
                  tag=case["tag"],
                  frequency_hz=case["frequency_hz"], source_dbv=case["level_dbv"],
                  source_resistance_ohm=case["source_resistance_ohm"], load_ohm=case["load_ohm"],
                  tstart_s=case["start_s"], tstop_s=case["stop_s"],
                  max_step_s=case["max_step_s"], native_samples=len(data),
                  integration_method=case["method"],
                  source_h1_rms_v=float(abs(fundamental[0]) / math.sqrt(2)),
                  primary_h1_rms_v=float(abs(fundamental[1]) / math.sqrt(2)),
                  output_h1_rms_v=float(abs(fundamental[2]) / math.sqrt(2)),
                  gain_source_db=db(transfer), gain_primary_db=db(port_transfer),
                  phase_source_deg=phase(transfer), phase_primary_deg=phase(port_transfer),
                  compression_source_db=db(ref_gain) - db(transfer),
                  compression_primary_db=db(ref_port_gain) - db(port_transfer),
                  h3_dbc=h3, h5_dbc=h5, h3_minus_h5_db=h3 - h5,
                  h3_status="resolved" if h3 > -120 else "below_reporting_floor",
                  h5_status="resolved" if h5 > -120 else "below_reporting_floor",
                  harmonics_basis="adaptive_analog_not_48k",
                  output_dc_mean_v=float(averages[2]), output_dc_fit_v=float(coeff[0, 2]),
                  output_drift_v_per_window=float(coeff[1, 2]),
                  source_peak_v=float(np.max(np.abs(data[:, 1]))),
                  primary_peak_v=float(np.max(np.abs(data[:, 2]))),
                  output_peak_v=float(np.max(np.abs(data[:, 3]))),
                  primary_dc_mean_v=float(averages[1]),
                  primary_current_dc_mean_a=float(averages[5]),
                  output_min_v=float(np.min(data[:, 3])), output_max_v=float(np.max(data[:, 3])),
                  cap1_peak_v=float(np.max(np.abs(data[:, 4]))),
                  cap1_mean_v=float(averages[3]), cap1_drift_v_per_window=float(coeff[1, 3]),
                  cap2_peak_v=float(np.max(np.abs(data[:, 5]))),
                  primary_current_h1_rms_a=float(abs(fundamental[5]) / math.sqrt(2)),
                  gain_early_late_db=db((late[2] / late[0]) / (early[2] / early[0])),
                  output_residual_rms_v=float(residual[2]))
    # Thresholds are reporting choices, not a hardware qualification.
    stationary = (abs(result["gain_early_late_db"]) < 0.01 and
                  abs(coeff[1, 2]) < 1e-4 * abs(fundamental[2]) and
                  abs(coeff[1, 3]) < 1e-3 * max(abs(harmonics[0, 3]), 1e-15))
    result["window_stationarity"] = "within_thresholds" if stationary else "drifting"
    count = int(round((case["stop_s"] - case["start_s"]) * RATE))
    uniform_t = case["start_s"] + np.arange(1, count + 1) / RATE
    sampled = np.column_stack([uniform_t] + [np.interp(uniform_t, data[:, 0], data[:, col])
                                             for col in range(1, data.shape[1])])
    # These are point samples, not an antialiased audio rendering.
    # Starting at tstart+1/fs avoids extrapolating the first omitted TSTART sample.
    if uniform_t[0] < data[0, 0] or uniform_t[-1] > data[-1, 0] + 1e-12:
        raise ValueError("48 kHz export would extrapolate")
    return result, sampled


def ac_rows(model, case, data):
    frequencies = data[:, 0]
    source, primary, output = [data[:, column] + 1j * data[:, column + 1]
                               for column in (1, 3, 5)]
    h, hp = output / source, output / primary
    delay = -np.gradient(np.unwrap(np.angle(h)), 2 * np.pi * frequencies)
    rows = [dict(model=model, netlist="netlists/" + case["case_id"] + ".cir",
                 frequency_hz=float(frequency), source_real_v=float(source[i].real),
                 source_imag_v=float(source[i].imag), primary_real_v=float(primary[i].real),
                 primary_imag_v=float(primary[i].imag), output_real_v=float(output[i].real),
                 output_imag_v=float(output[i].imag), gain_source_db=db(h[i]),
                 gain_primary_db=db(hp[i]), phase_source_deg=phase(h[i]),
                 group_delay_s=float(delay[i])) for i, frequency in enumerate(frequencies)]
    return rows, (frequencies, h, hp)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ngspice", default=shutil.which("ngspice"))
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--models", nargs="+", choices=list(MODELS), default=list(MODELS))
    parser.add_argument("--frequencies", nargs="+", type=int, default=list(FREQUENCIES))
    parser.add_argument("--levels", nargs="+", type=float, default=list(LEVELS))
    args = parser.parse_args()
    if not args.ngspice:
        parser.error("ngspice fehlt; --ngspice /pfad/zu/ngspice verwenden")
    for directory in (HERE / "netlists", HERE / "logs"):
        directory.mkdir(exist_ok=True)
    parameters = adapt_model()
    version = subprocess.run([args.ngspice, "--version"], capture_output=True, text=True, check=True)
    write_text(HERE / "ngspice-version.txt", version.stdout)
    metadata = dict(original_model="../sauce/xformer.lib", original_sha256=sha256(SOURCE),
                    adapted_model="xformer-ngspice.inc", adapted_sha256=sha256(HERE / "xformer-ngspice.inc"),
                    script_sha256=sha256(Path(__file__)), parameters=parameters,
                    sample_rate_hz=RATE, waveform_columns=["time_s", "source_v", "primary_v",
                        "output_v", "cap1_v", "cap2_v", "primary_current_a"],
                    source_convention="differential open-circuit RMS, DC=0, Rs=200 ohm total",
                    load_convention="8 ohm resistive; own test fixture",
                    harmonic_reporting_floor_dbc=-120,
                    waveform_storage="original first/last observation cycle; explicit time gap; float64",
                    uniform_export="48k point samples by linear interpolation; NO antialias filter",
                    harmonic_fit="time-weighted regression, H1..H9 plus DC/linear/quadratic drift",
                    ngspice_executable=str(Path(args.ngspice).resolve()),
                    ngspice_executable_sha256=sha256(Path(args.ngspice)), runs=[])
    tasks = []
    for model in args.models:
        canonical = make_case(model, 1000, 0)
        canonical["case_id"] = model
        write_text(HERE / (model + ".cir"), circuit(canonical))
        for frequency in args.frequencies:
            for level in args.levels:
                tasks.append(make_case(model, frequency, level))
    rows_by_model = {model: [] for model in args.models}
    waves = {model: {} for model in args.models}
    refs = {}
    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        for index, (case, arrays, info) in enumerate(pool.map(
                lambda item: run_ngspice(args.ngspice, item), tasks)):
            model = case["model"]
            if model not in refs:
                rows, refs[model] = ac_rows(model, case, arrays["ac"])
                write_csv(HERE / (model + "-ac.csv"), rows,
                          ["Measured ngspice AC at DC=0; adaptive DDT realization; original coefficients.",
                           "200 points/decade; Rs=200 ohm differential; RL=8 ohm."])
            row, sampled = analyze(case, arrays, refs[model])
            rows_by_model[model].append(row)
            waves[model].update(archive_waveforms(case, arrays["transient"], sampled))
            info["full_native_array_sha256"] = hashlib.sha256(
                arrays["transient"].astype("<f8").tobytes()).hexdigest()
            metadata["runs"].append(dict(**case, **info))
            print(f"[{index + 1}/{len(tasks)}] {case['case_id']}: "
                  f"H={row['gain_source_db']:.6f} dB, "
                  f"comp={row['compression_source_db']:.6f} dB, "
                  f"{row['window_stationarity']}", flush=True)
    for model in args.models:
        write_csv(HERE / (model + "-results.csv"), rows_by_model[model],
                  ["Measured by ngspice; finite observation windows, NOT assumed steady state.",
                   "Pegel dBV = differential source RMS before Rs; primary level measured separately.",
                   "Compression = 20 log10(abs(H_ac)/abs(H1)); negative = expansion.",
                   "H3/H5 measured at native adaptive times, including harmonics > 24 kHz.",
                   "Values <= -120 dBc are raw diagnostics, not resolved distortion.",
                   f"Model SHA256: {sha256(SOURCE)}"])
        np.savez_compressed(HERE / (model + "-waveforms.npz"), **waves[model])
    # Preserve direct original-library failures as evidence, not accepted data.
    for model in args.models:
        case = make_case(model, 1000, 0, tag="literal")
        case, arrays, info = run_ngspice(args.ngspice, case, realization="literal")
        np.savez_compressed(HERE / (model + "-literal.npz"), **arrays)
        metadata["runs"].append(dict(**case, **info))
    write_json(HERE / "run-manifest.json", metadata)


if __name__ == "__main__":
    main()
