# Local development recipe. Source path inside MPB container is /root/source.
GREEN_STRIPE_76_VERSION = 0.1.0
GREEN_STRIPE_76_SITE_METHOD = local
GREEN_STRIPE_76_SITE = /root/source
GREEN_STRIPE_76_LICENSE = MIT, ISC (LV2 ABI header)
GREEN_STRIPE_76_LICENSE_FILES = LICENSE
GREEN_STRIPE_76_DEPENDENCIES =
GREEN_STRIPE_76_BUNDLES = green-stripe-76.lv2
GREEN_STRIPE_76_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)

define GREEN_STRIPE_76_BUILD_CMDS
	$(GREEN_STRIPE_76_TARGET_MAKE) BUILD_DIR=build/mpb
endef

define GREEN_STRIPE_76_INSTALL_TARGET_CMDS
	$(GREEN_STRIPE_76_TARGET_MAKE) BUILD_DIR=build/mpb install DESTDIR=$(TARGET_DIR) PREFIX=/usr
endef

$(eval $(generic-package))
