// Generated by tools/generate.py; SPDX-License-Identifier: MIT.
// GR needle driver (modgui javascript, api_version 3). The needle asset
// points to 0 dB GR at the left scale end, so the rotation is relative to
// rest: 0 dB GR = 0 deg, 20 dB GR = +90 deg (clamped at the scale end).
// The face variant follows the compression state via root classes.
function (event, funcs) {
    var REST_DEG = -0.0, MAX_DB = 20.0, SWEEP = 90.0;
    function clamp(x, lo, hi) { return x < lo ? lo : (x > hi ? hi : x); }
    function setState(on) {
        var root = event.icon.find('.gs76');
        root.addClass(on ? 'gs-comp-on' : 'gs-comp-off');
        root.removeClass(on ? 'gs-comp-off' : 'gs-comp-on');
    }
    function setNeedle(grDb) {
        var reduction = clamp(-grDb, 0.0, MAX_DB);
        var deg = REST_DEG + reduction / MAX_DB * SWEEP;
        event.icon.find('.gs-vu-needle').css('transform', 'rotate(' + deg + 'deg)');
    }
    if (event.type === 'start') {
        var ports = event.ports || [];
        for (var i in ports) {
            if (ports[i].symbol === 'compression') setState(ports[i].value > 0.5);
            else if (ports[i].symbol === 'gr_db') setNeedle(ports[i].value);
        }
    } else if (event.type === 'change') {
        if (event.symbol === 'compression') setState(event.value > 0.5);
        else if (event.symbol === 'gr_db') setNeedle(event.value);
    }
}
