#!/usr/bin/env python3
"""Generate shared constants, LV2 metadata, JSFX wrappers and preset data.

Only stdlib is required. --check compares without writing any files.
"""
import argparse
import base64
import json
from pathlib import Path
from transformer_model import generated as transformer_files

ROOT = Path(__file__).resolve().parents[1]
PREFIX = "https://github.com/j4yj03/mod-1175-lv2#green-stripe-76-"
TTL_PREFIXES = '''@prefix lv2: <http://lv2plug.in/ns/lv2core#> .
@prefix doap: <http://usefulinc.com/ns/doap#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix units: <http://lv2plug.in/ns/extensions/units#> .
@prefix pprops: <http://lv2plug.in/ns/ext/port-props#> .
@prefix pg: <http://lv2plug.in/ns/ext/port-groups#> .
@prefix mod: <http://moddevices.com/ns/mod#> .
@prefix modgui: <http://moddevices.com/ns/modgui#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
'''


def number(value):
    return format(value, '.17g') if isinstance(value, float) else str(value)


def eel_number(value):
    # EEL2 does not accept C-style scientific literals in all hosts.
    text = number(value)
    if 'e' in text.lower():
        from decimal import Decimal
        text = format(Decimal(text), 'f')
    return text


def eel_lookup(name, values):
    # EEL2 globals share one storage pool; an indexed store past a declared array
    # size does not grow the array but overwrites the following variable. The mode
    # tables are therefore emitted as lookup functions instead of indexed globals.
    # EEL2 also rejects a negative literal or a parenthesis directly after `?`, so
    # the chain uses local assignment statements like the rest of the EEL2 core.
    body = [f'  v={eel_number(values[-1])};']
    body += [f'  m==={i} ? v={eel_number(x)};' for i, x in enumerate(values[:-1])]
    body += ['  v;', ');']
    return '\n'.join([f'function {name}(m) local(v) ('] + body)


def model_files(model):
    cpp = ['// Generated by tools/generate.py; edit data/model.json.',
           '#ifndef GREEN_STRIPE_MODEL_CONSTANTS_HPP',
           '#define GREEN_STRIPE_MODEL_CONSTANTS_HPP',
           'namespace greenstripe { namespace model {']
    eel = ['// Generated by tools/generate.py; SPDX-License-Identifier: MIT', '@init',
           'function gs_model_init() (']
    lookups = {'ratios': 'gs_ratio_of', 'thresholds_dbfs': 'gs_threshold_of',
               'knees_db': 'gs_knee_of'}
    addresses = {'halfband_stage1': ('gs_coefs1', 0),
                 'halfband_stage2': ('gs_coefs2', 8)}
    functions = []
    for key, value in model.items():
        if isinstance(value, str):
            continue
        if isinstance(value, list):
            cpp.append(f'static const double {key}[] = {{{", ".join(map(number, value))}}};')
            if key in lookups:
                functions.append(eel_lookup(lookups[key], value))
                continue
            variable, address = addresses[key]
            eel.append(f'  {variable}={address};')
            eel.extend(f'  {variable}[{i}]={eel_number(x)};' for i, x in enumerate(value))
        else:
            kind = 'unsigned' if isinstance(value, int) else 'double'
            cpp.append(f'static const {kind} {key} = {number(value)};')
            eel.append(f'  gs_{key}={eel_number(value)};')
    cpp += ['} }', '#endif', '']
    eel += [');', ''] + [line for f in functions for line in (f, '')]
    return {'src/dsp/ModelConstants.hpp': '\n'.join(cpp),
            'jsfx/GreenStripe76-Model.jsfx-inc': '\n'.join(eel)}


def appended_value(q, preset):
    """Value an appended control takes on a preset recall.

    Oversampling resets to its default on every recall: it is a quality/CPU
    choice, not part of the instrument sound. The transformer is a tone choice
    and is read from the preset, so a preset named for a vintage, mojo or huge
    character can bring its transformer stage with it. Only the few presets that
    set it carry a non-default value; everything else recalls to None.
    """
    if q['symbol'] == 'oversampling':
        return q['default']
    return preset.get(q['symbol'], q['default'])


def group_uri(variant, symbol):
    """Gruppen-URI: Plugin-Fragment plus Gruppen-Plugin-Suffix, ein Fragment."""
    return f'{PREFIX}{variant}-group-{symbol}'


def port(index, p, variant):
    properties = []
    if p.get('labels'):
        properties += ['lv2:integer', 'lv2:enumeration']
    if p.get('toggle'):
        properties += ['lv2:integer', 'lv2:toggled']
    if p.get('connection_optional'):
        properties += ['lv2:connectionOptional']
    lines = [f'    [ a lv2:InputPort, lv2:ControlPort; lv2:index {index};',
             f'      lv2:symbol "{p["symbol"]}"; lv2:name "{p["name"]}";']
    if p.get('group'):
        lines.append(f'      pg:group <{group_uri(variant, p["group"])}>;')
    lines += [f'      lv2:shortName "{p["short"]}"; lv2:default {number(p["default"])};',
              f'      lv2:minimum {number(p["min"])}; lv2:maximum {number(p["max"])};']
    if p.get('unit'):
        lines.append(f'      units:unit units:{p["unit"]};')
    if p.get('designation'):
        lines.append(f'      lv2:designation lv2:{p["designation"]};')
    if properties:
        lines.append('      lv2:portProperty ' + ', '.join(properties) + ';')
    for i, name in enumerate(p.get('labels', [])):
        lines.append(f'      lv2:scalePoint [ rdfs:label "{name}"; rdf:value {i} ];')
    steps = min(601, round((p['max'] - p['min']) / p['step']) + 1)
    lines.append(f'      pprops:rangeSteps {steps} ]')
    return '\n'.join(lines)


def output_port(index, p, variant):
    """Output control port (e.g. the measured gain reduction).

    Outputs are never preset-addressable and never appear in presets.ttl;
    the host reads them, the GUI only listens.
    """
    lines = [f'    [ a lv2:OutputPort, lv2:ControlPort; lv2:index {index};',
             f'      lv2:symbol "{p["symbol"]}"; lv2:name "{p["name"]}";']
    if p.get('group'):
        lines.append(f'      pg:group <{group_uri(variant, p["group"])}>;')
    lines += [f'      lv2:shortName "{p["short"]}"; lv2:default {number(p["default"])};',
              f'      lv2:minimum {number(p["min"])}; lv2:maximum {number(p["max"])};']
    if p.get('unit'):
        lines.append(f'      units:unit units:{p["unit"]};')
    lines.append('      lv2:portProperty lv2:connectionOptional;')
    steps = min(601, round((p['max'] - p['min']) / p['step']) + 1)
    lines.append(f'      pprops:rangeSteps {steps} ]')
    return '\n'.join(lines)


GRMETER_JS = '''// Generated by tools/generate.py; SPDX-License-Identifier: MIT.
// GR needle driver (modgui javascript, api_version 3). The needle asset
// points to 0 dB GR at the left scale end, so the rotation is relative to
// rest: 0 dB GR = 0 deg, 30 dB GR = +90 deg (clamped at the scale end).
// The face variant follows the compression state via root classes.
function (event, funcs) {
    var REST_DEG = -0.0, MAX_DB = 30.0, SWEEP = 90.0;
    function clamp(x, lo, hi) { return x < lo ? lo : (x > hi ? hi : x); }
    function setState(on) {
        var root = event.icon.find('.gs76-root');
        root.addClass(on ? 'gs-comp-on' : 'gs-comp-off');
        root.removeClass(on ? 'gs-comp-off' : 'gs-comp-on');
    }
    function setNeedle(grDb) {
        var reduction = clamp(-grDb, 0.0, MAX_DB);
        var deg = REST_DEG + reduction / MAX_DB * SWEEP;
        event.icon.find('.gs-vu-needle').css('transform', 'rotate(' + deg + 'deg)');
    }
    if (event.type === 'start') {
        var ports = event.ports || [];
        for (var i in ports) {
            if (ports[i].symbol === 'compression') setState(ports[i].value > 0.5);
            else if (ports[i].symbol === 'gr_db') setNeedle(ports[i].value);
        }
    } else if (event.type === 'change') {
        if (event.symbol === 'compression') setState(event.value > 0.5);
        else if (event.symbol === 'gr_db') setNeedle(event.value);
    }
}
'''


def metadata(parameters, presets, model):
    files = {}
    _, minor, micro = map(int, model['version'].split('.'))
    bundle = 'lv2/green-stripe-76.lv2/'
    groups = json.loads((ROOT / 'data/port_groups.json').read_text(encoding='utf-8'))['groups']
    group_types = {g['symbol']: g.get('type', 'input') for g in groups}
    group_names = {g['symbol']: g['name'] for g in groups}
    manifest = [TTL_PREFIXES]
    gui = [TTL_PREFIXES]
    preset_text = [TTL_PREFIXES]
    for stereo in (False, True):
        variant = 'stereo' if stereo else 'mono'
        uri = PREFIX + variant
        manifest.append(f'<{uri}> a lv2:Plugin; lv2:binary <green-stripe-76.so>; '
                        f'rdfs:seeAlso <{variant}.ttl>, <modgui.ttl> .')
        ports = []
        audio = [('in_l', 'Input L', True), ('in_r', 'Input R', True),
                 ('out_l', 'Output L', False), ('out_r', 'Output R', False)] if stereo else [
                 ('in', 'Input', True), ('out', 'Output', False)]
        audio_group = {'in_l': 'audio_in', 'in_r': 'audio_in', 'in': 'audio_in',
                       'out_l': 'audio_out', 'out_r': 'audio_out', 'out': 'audio_out'}
        for i, (symbol, label, is_input) in enumerate(audio):
            ports.append(f'    [ a lv2:{"Input" if is_input else "Output"}Port, lv2:AudioPort; '
                         f'lv2:index {i}; lv2:symbol "{symbol}"; lv2:name "{label}"; '
                         f'pg:group <{group_uri(variant, audio_group[symbol])}> ]')
        controls = [p for p in parameters if stereo or not p.get('stereo_only')]
        existing_controls = [p for p in controls
                             if not p.get('lv2_append') and not p.get('lv2_output')]
        appended_controls = [p for p in controls if p.get('lv2_append')]
        outputs = [p for p in controls if p.get('lv2_output')]
        ports += [port(len(audio) + i, p, variant) for i, p in enumerate(existing_controls)]
        latency_index = len(audio) + len(existing_controls)
        ports.append(f'    [ a lv2:OutputPort, lv2:ControlPort; lv2:index {latency_index}; '
                     'lv2:symbol "latency"; lv2:name "Nominal latency"; '
                     'lv2:designation lv2:latency; lv2:portProperty lv2:integer, pprops:notOnGUI; '
                      'units:unit units:frame; lv2:minimum 0; lv2:maximum 32; lv2:default 0 ]')
        ports += [port(latency_index + 1 + i, p, variant) for i, p in enumerate(appended_controls)]
        ports += [output_port(latency_index + 1 + len(appended_controls) + i, p, variant)
                  for i, p in enumerate(outputs)]
        # Gruppenressourcen: audio_in/audio_out plus jede referenzierte
        # Steuergruppe; Symbole muessen portfrei bleiben (pg-Spec).
        port_symbols = {s for s, _, _ in audio} | {p['symbol'] for p in controls}
        used_groups = []
        for symbol in ['audio_in', 'audio_out'] + [p['group'] for p in controls if p.get('group')]:
            if symbol not in used_groups:
                used_groups.append(symbol)
        assert not (port_symbols & set(used_groups)), port_symbols & set(used_groups)
        group_blocks = []
        for symbol in used_groups:
            if symbol == 'audio_in':
                types = ('pg:StereoGroup, ' if stereo else 'pg:MonoGroup, ') + 'pg:InputGroup'
                name = 'Input'
            elif symbol == 'audio_out':
                types = ('pg:StereoGroup, ' if stereo else 'pg:MonoGroup, ') + 'pg:OutputGroup'
                name = 'Output'
            else:
                types = 'pg:OutputGroup' if group_types[symbol] == 'output' else 'pg:InputGroup'
                name = group_names[symbol]
            group_blocks.append(
                f'<{group_uri(variant, symbol)}> a {types}; lv2:symbol "{symbol}"; '
                f'lv2:name "{name}" .')
        files[bundle + variant + '.ttl'] = TTL_PREFIXES + f'''
<{uri}> a lv2:Plugin, lv2:CompressorPlugin;
    doap:name "Green Stripe 76 {variant.title()}";
    doap:license <https://opensource.org/license/mit>;
    doap:maintainer [ foaf:name "Green Stripe 76 contributors";
        foaf:homepage <https://github.com/j4yj03/mod-1175-lv2> ];
    mod:brand "GreenStripe"; mod:label "GS76 {variant.title()}";
    lv2:minorVersion {minor}; lv2:microVersion {micro};
    lv2:optionalFeature lv2:hardRTCapable;
    pg:mainInput <{group_uri(variant, 'audio_in')}>;
    pg:mainOutput <{group_uri(variant, 'audio_out')}>;
    rdfs:comment "Independent FET feedback adaptation. Selectable Off/2x/4x oversampling, default Off, programme-dependent recovery, All Buttons, amplifier colour and refit-able input transformer profiles. No lookahead or brickwall guarantee. Nominal IIR latency is frequency dependent. Input/Output are digital dB gains. See project documentation.";
    lv2:port
''' + ',\n'.join(ports) + ' .\n' + '\n'.join(group_blocks) + '\n'
        gui_ports = [p for p in controls if p['symbol'] != 'enabled']
        monitored = ',\n'.join(f'    [ lv2:symbol "{p["symbol"]}" ]' for p in outputs)
        gui.append(f'''<{uri}> modgui:gui [
    modgui:resourcesDirectory <modgui>;
    modgui:iconTemplate <modgui/icon-{variant}.html>;
    modgui:stylesheet <modgui/green-stripe.css>;
    modgui:javascript <modgui/grmeter.js>;
    modgui:screenshot <modgui/screenshot-{variant}.png>;
    modgui:thumbnail <modgui/thumbnail-{variant}.png>;
    modgui:monitoredOutputs {monitored} ;
    modgui:port
''' + ',\n'.join(f'    [ lv2:index {i}; lv2:symbol "{p["symbol"]}"; '
                      f'lv2:name "{p["name"]}" ]' for i, p in enumerate(gui_ports)) + ' ] .\n')
        for i, preset in enumerate(presets):
            preset_uri = PREFIX + f'preset-{variant}-{i+1:02d}'
            manifest.append(f'<{preset_uri}> a pset:Preset; lv2:appliesTo <{uri}>; '
                            f'rdfs:label "{preset["name"]}"; rdfs:seeAlso <presets.ttl> .')
            values = dict(preset, enabled=1, stereo_link=preset['link'])
            # Oversampling is a quality/CPU choice, not an instrument value, so a
            # recall always starts from Off. The transformer is a tone choice and
            # is therefore carried per preset; it defaults to None.
            for q in controls:
                if q.get('lv2_append'):
                    values[q['symbol']] = appended_value(q, preset)
            preset_text.append(f'<{preset_uri}> a pset:Preset; lv2:appliesTo <{uri}>; '
                              f'rdfs:label "{preset["name"]}"; lv2:port\n' + ',\n'.join(
                                  f'    [ lv2:symbol "{p["symbol"]}"; pset:value {number(values[p["symbol"]])} ]'
                                  for p in controls if not p.get('lv2_output')) + ' .\n')
        files[bundle + f'modgui/icon-{variant}.html'] = gui_html(stereo, parameters,
                                                                 model['version'])
    files[bundle + 'manifest.ttl'] = '\n'.join(manifest) + '\n'
    files[bundle + 'modgui.ttl'] = '\n'.join(gui) + '\n'
    files[bundle + 'presets.ttl'] = '\n'.join(preset_text) + '\n'
    files[bundle + 'modgui/grmeter.js'] = GRMETER_JS
    return files


def gui_html(stereo, parameters, version):
    """Panel markup for the MOD GUI.

    Joined rack modules with full-height GAIN/TIME sections and individually
    oriented Phillips slots. ENGINE carries the unframed product name; the
    knob modules have no headings and share two aligned rows. All knob labels are neutral, and numeric
    values sit in small inset fields. The bypass has no printed caption.
    The footer plate shows the variant under the product line and the product
    version (revision as third digit) below it. No GR or level meters.
    """
    def spec(symbol):
        return next(p for p in parameters if p['symbol'] == symbol)

    def labels(symbol, override=None):
        s = spec(symbol)
        return override if override is not None else s.get('labels', [])

    def knob(symbol, label, scale=('Min.', 'Max.')):
        """Knob with its end-stop legend.

        The legend sits beside the knob rather than under it: a second text row
        would make a two-knob bay taller than a bay that also carries a select,
        and the bay bodies are centred, so the bays would no longer line up.
        """
        return (f'<div class="gs-control">'
                f'<div class="gs-knob-row">'
                f'<i class="gs-scale">{scale[0]}</i>'
                f'<div class="gs-knob" mod-role="input-control-port" mod-port-symbol="{symbol}" '
                f'mod-widget="film"></div>'
                f'<i class="gs-scale">{scale[1]}</i>'
                f'</div>'
                f'<label>{label}</label>'
                f'<span class="gs-value" mod-role="input-control-value" mod-port-symbol="{symbol}"></span></div>')

    def select(symbol, label, override=None):
        options = labels(symbol, override)
        caption = f'<label>{label}</label>' if label else ''
        return (f'<div class="gs-field">{caption}'
                f'<select mod-role="input-control-port" mod-port-symbol="{symbol}" '
                f'mod-widget="select" aria-label="{spec(symbol)["name"]}">'
                + ''.join(f'<option value="{i}">{t}</option>' for i, t in enumerate(options))
                + '</select></div>')

    def switch(symbol):
        """MOD on/off classes select the caption inside the moving handle."""
        return (f'<div class="gs-field">'
                f'<div class="gs-switch" mod-role="input-control-port" '
                f'mod-port-symbol="{symbol}" mod-widget="switch" aria-label="{spec(symbol)["name"]}">'
                f'<i><span class="gs-switch-on">COMP ON</span>'
                f'<span class="gs-switch-off">COMP OFF</span></i></div></div>')

    inputs = ''.join(f'<div class="gs-jack" mod-role="input-audio-port" mod-port-symbol="{x}"></div>'
                     for x in (['in_l', 'in_r'] if stereo else ['in']))
    outputs = ''.join(f'<div class="gs-jack" mod-role="output-audio-port" mod-port-symbol="{x}"></div>'
                      for x in (['out_l', 'out_r'] if stereo else ['out']))
    transformer_labels = ['No Transformer' if name == 'None' else f'{name} Transformer'
                          for name in labels('transformer')]
    def screws(inner, angles):
        # Rotate only the slots: bezel lighting/shadows always point down-right.
        cls = 'gs-screw-i' if inner else 'gs-screw'
        return ''.join(f'<i class="{cls} {cls}-{corner}" aria-hidden="true">'
                       f'<span class="gs-slot" style="transform:rotate({angle}deg)"></span></i>'
                       for corner, angle in zip(('tl', 'tr', 'bl', 'br'), angles))

    return f'''<!-- Generated by tools/generate.py. Joined rack modules, full-height
     GAIN/TIME divider, individually oriented corner screws, neutral knob labels
     and inset value fields. Unframed product title on green; knob modules untitled.
     Input/Attack/Mix and Output/Release/Colour share two horizontal rows.
     Unlabelled bypass beside the amber pilot. Light from upper left.
     Drag handles: full frame ring (top/left/right/bottom rails), footer plate.
     Footer plate carries the variant and the version+revision line.
     The ENGINE bay carries the GR VU meter; there are no input meters. -->
<div class="gs76{{{{{{cns}}}}}} gs76-root">
<div class="mod-drag-handle gs-drag gs-drag-top" mod-role="drag-handle" title="Paneel verschieben"></div>
{screws(False, (0, 45, 18, 67))}
<div class="mod-drag-handle gs-drag gs-drag-left" mod-role="drag-handle" title="Paneel verschieben"></div>
<div class="mod-drag-handle gs-drag gs-drag-right" mod-role="drag-handle" title="Paneel verschieben"></div>
<div class="gs-bays">
<div class="gs-bay gs-bay-wide"><div class="gs-pair"><section>{screws(True, (8, 31, 54, 79))}<div class="gs-body gs-body-knobs">{knob('input', 'INPUT')}{knob('output', 'OUTPUT')}</div></section><section>{screws(True, (13, 38, 61, 84))}<div class="gs-body gs-body-knobs">{knob('attack', 'ATTACK', ('Slow', 'Fast'))}{knob('release', 'RELEASE', ('Slow', 'Fast'))}</div></section></div></div>
<div class="gs-bay gs-bay-engine">{screws(True, (4, 26, 49, 72))}<div class="gs-brand"><img src="/resources/assets/logo.png{{{{{{ns}}}}}}" alt="Green Stripe 76" class="gs-logo"></div><div class="gs-body gs-body-engine"><div class="gs-vuwrap"><img class="gs-vu gs-vu-on" src="/resources/assets/vumeter-on.png{{{{{{ns}}}}}}" alt="Gain Reduction (COMP ON)"><img class="gs-vu gs-vu-off" src="/resources/assets/vumeter-off.png{{{{{{ns}}}}}}" alt="Gain Reduction (COMP OFF)"><img class="gs-vu-needle" src="/resources/assets/vumeter-needle.png{{{{{{ns}}}}}}" alt=""><img class="gs-vu gs-vu-hub" src="/resources/assets/vumeter-hub.png{{{{{{ns}}}}}}" alt=""></div><div class="gs-engine-controls">{select('ratio', '')}{switch('compression')}</div></div></div>
<div class="gs-bay">{screws(True, (22, 43, 58, 88))}<div class="gs-body gs-body-knobs">{knob('mix', 'MIX')}{knob('colour', 'COLOUR')}{select('transformer', '', transformer_labels)}</div></div>
</div>
<footer>
<div class="gs-plate gs-drag-foot mod-drag-handle" mod-role="drag-handle"><b>FET COMPRESSOR/LIMITER EMULATION</b><span>{'STEREO' if stereo else 'MONO'}</span><span class="gs-plate-version">{version}</span></div>
<div class="gs-power">
<div class="gs-bypass" mod-role="bypass" mod-widget="bypass" title="Bypass" aria-label="Bypass"></div>
<div class="gs-lamp" title="Betriebsanzeige"></div>
</div>
</footer>
<div class="mod-drag-handle gs-drag gs-drag-bottom" mod-role="drag-handle" title="Paneel verschieben"></div>
<div class="gs-inputs">{inputs}</div><div class="gs-outputs">{outputs}</div>
</div>
'''
def jsfx_files(parameters, presets, model):
    files = {}
    preset_eel = ['// Generated instrument starting points; not hardware measurements.', '@init',
                  'function gs_apply_preset(which) (']
    # Oversampling always resets (quality/CPU, not instrument value); the
    # transformer is carried per preset. Both are written through
    # appended_value() so LV2, JSFX and RPL cannot drift apart.
    appended = [p for p in parameters if p.get('jsfx_slider', 0) >= 12]
    for i, p in enumerate(presets):
        preset_eel.append(f'  which=={i+1} ? (')
        values = [p[x] for x in ('input','output','attack','release','ratio','mix','colour','compression')]
        values += [1, p['link']]
        preset_eel += [f'    slider{j+1}={number(x)};' for j, x in enumerate(values)]
        preset_eel += [f'    slider{q["jsfx_slider"]}={number(appended_value(q, p))};' for q in appended]
        preset_eel.append('  );')
    preset_eel += ['  sliderchange(1023);', ');', '']
    files['jsfx/GreenStripe76-Presets.jsfx-inc'] = '\n'.join(preset_eel)
    for stereo in (False, True):
        variant = 'Stereo' if stereo else 'Mono'
        rpl = [f'<REAPER_PRESET_LIBRARY "Green Stripe 76 {variant}"']
        for preset in presets:
            values = [preset[x] for x in ('input','output','attack','release','ratio','mix','colour','compression')]
            # slider9 enabled, slider10 link, slider11 preset selector, slider12
            # oversampling, slider13 transformer. Both appended controls go
            # through appended_value(), so oversampling resets to Off while a
            # preset may keep its own transformer stage.
            values += [1, preset['link'], 0] + [number(appended_value(q, preset))
                                                for q in appended]
            state = ' '.join([number(x) for x in values] + ['-']*(64-len(values)))
            payload = base64.b64encode((state + ' "' + preset['name'] + '"\x00').encode('utf-8')).decode('ascii')
            rpl += [f'  <PRESET "{preset["name"]}"', '    '+payload, '  >']
        rpl += ['>', '']
        files[f'jsfx/GreenStripe76-{variant}.rpl'] = '\n'.join(rpl)
        lines = [f'desc:Green Stripe 76 {variant}', 'author:Green Stripe 76 contributors',
                 f'version:{model["version"]}', 'tags:dynamics compressor limiter fet',
                 '// SPDX-License-Identifier: MIT',
                 'options:maxmem=8192 prealloc=8192 gfx_hz=30',
                 'import GreenStripe76-Core.jsfx-inc',
                 'import GreenStripe76-Presets.jsfx-inc',
                 'import GreenStripe76-UI.jsfx-inc']
        for i, p in enumerate(parameters):
            label = p['name']
            if p.get('unit') == 'db': label += ' (dB)'
            if p.get('unit') == 'pc': label += ' (%)'
            if not stereo and p.get('stereo_only'): label = '-' + label
            labels = '{' + ','.join(p['labels']) + '}' if p.get('labels') else '{Off,On}' if p.get('toggle') else ''
            slider_index = p.get('jsfx_slider', i + 1)
            if not slider_index:
                continue  # LV2-only output ports have no JSFX slider.
            lines.append(f'slider{slider_index}:{p["default"]}<{p["min"]},{p["max"]},{p["step"]}{labels}>{label}')
        names = 'Custom,' + ','.join(p['name'] for p in presets)
        lines.append(f'slider11:0<0,{len(presets)},1{{{names}}}>Instrument preset')
        # Control sliders are derived, not hardcoded: appended ports (oversampling,
        # transformer) must take part in the change detection and in gs_set, or a
        # manual change would leave a stale instrument preset selected.
        control_sliders = sorted(s for s in (p.get('jsfx_slider', i + 1)
                                             for i, p in enumerate(parameters)) if s)
        detect = ' || '.join(f'slider{s}!=gs_prev{s}' for s in control_sliders)
        capture = ' '.join(f'gs_prev{s}=slider{s};' for s in control_sliders)
        set_call = ','.join(f'slider{s}' for s in control_sliders)
        lines += ['in_pin:Input L', 'in_pin:Input R', 'out_pin:Output L', 'out_pin:Output R',
                  '', '@init', 'ext_nodenorm=1; ext_tail_size=-1; ext_gr_meter=0;',
                  'gfx_ext_retina=1;', f'gs_stereo={1 if stereo else 0};',
                  f'#gs_ver="{model["version"]}";',
                  'gs_engine.gs_reset(gs_stereo); gs_rate=srate;',
                  'gs_inL.gs_meter_init(); gs_inR.gs_meter_init();',
                  'gs_outL.gs_meter_init(); gs_outR.gs_meter_init();',
                  'gs_grL=gs_grR=gs_peakGR=0; gs_last_preset=slider11; gs_have_controls=0;',
                  'gs_meter_decay=exp(-1/(0.35*max(8000,srate)));',
                  'gs_meter_rms=1-exp(-1/(0.3*max(8000,srate)));',
                  '', '@slider',
                  'slider11!=gs_last_preset ? (slider11>0 ? gs_apply_preset(slider11); gs_last_preset=slider11;) : (',
                  f'  gs_have_controls && ({detect}) ? (',
                  '    slider11=0; gs_last_preset=0; sliderchange(slider11);',
                  '  );', ');',
                  f'{capture} gs_have_controls=1;',
                  f'gs_engine.gs_set({set_call});',
                  '', '@block', 'srate!=gs_rate ? (',
                  '  gs_engine.gs_reset(gs_stereo); gs_rate=srate;',
                  '  gs_meter_decay=exp(-1/(0.35*max(8000,srate)));',
                  '  gs_meter_rms=1-exp(-1/(0.3*max(8000,srate)));', ');',
                  f'gs_engine.gs_set({set_call});',
                  'pdc_delay=gs_engine.gs_latency(); pdc_bot_ch=0; pdc_top_ch=2;',
                  'atomic_set(gs_ui_os_active,gs_engine.os_active);',
                  'ext_gr_meter=gs_peakGR; gs_peakGR=0;',
                  'atomic_set(gs_audio_time,time_precise());',
                  'atomic_set(gs_ui_inL,gs_gain_db(gs_inL.peak)); atomic_set(gs_ui_inR,gs_gain_db(gs_stereo ? gs_inR.peak : gs_inL.peak));',
                  'atomic_set(gs_ui_outL,gs_gain_db(gs_outL.peak)); atomic_set(gs_ui_outR,gs_gain_db(gs_stereo ? gs_outR.peak : gs_outL.peak));',
                  'atomic_set(gs_ui_inRmsL,gs_gain_db(sqrt(max(0,gs_inL.rms))));',
                  'atomic_set(gs_ui_inRmsR,gs_gain_db(sqrt(max(0,gs_stereo ? gs_inR.rms : gs_inL.rms))));',
                  'atomic_set(gs_ui_rmsL,gs_gain_db(sqrt(max(0,gs_outL.rms))));',
                  'atomic_set(gs_ui_rmsR,gs_gain_db(sqrt(max(0,gs_stereo ? gs_outR.rms : gs_outL.rms))));',
                  'atomic_set(gs_ui_holdL,gs_gain_db(gs_outL.hold)); atomic_set(gs_ui_holdR,gs_gain_db(gs_stereo ? gs_outR.hold : gs_outL.hold));',
                  'atomic_set(gs_ui_inHoldL,gs_gain_db(gs_inL.hold)); atomic_set(gs_ui_inHoldR,gs_gain_db(gs_stereo ? gs_inR.hold : gs_inL.hold));',
                  'atomic_set(gs_ui_inClipL,gs_inL.clip); atomic_set(gs_ui_inClipR,gs_stereo ? gs_inR.clip : gs_inL.clip);',
                  'atomic_set(gs_ui_grL,gs_grL); atomic_set(gs_ui_grR,gs_grR);',
                  'atomic_set(gs_ui_clipL,gs_outL.clip); atomic_set(gs_ui_clipR,gs_stereo ? gs_outR.clip : gs_outL.clip);',
                  '', '@sample',
                  'gs_rawL=gs_bound(gs_finite(spl0,0),-256,256);',
                  'gs_rawR=gs_bound(gs_finite(spl1,0),-256,256);',
                  'gs_stereo ? gs_engine.gs_process(gs_rawL,gs_rawR) : gs_engine.gs_process(gs_rawL,gs_rawL);',
                  'spl0=gs_engine.outL; spl1=gs_engine.outR;',
                  'gs_inL.gs_meter_sample(gs_rawL); gs_outL.gs_meter_sample(spl0);',
                  'gs_stereo ? (gs_inR.gs_meter_sample(gs_rawR); gs_outR.gs_meter_sample(spl1););',
                  'gs_peakGR=min(gs_peakGR,min(gs_engine.grL,gs_engine.grR));',
                  'gs_grL=max(-gs_engine.grL,gs_grL*gs_meter_decay);',
                  'gs_grR=max(-gs_engine.grR,gs_grR*gs_meter_decay);',
                  '', '@gfx 820 380', 'gs_draw_ui(gs_stereo);', '']
        files[f'jsfx/GreenStripe76-{variant}.jsfx'] = '\n'.join(lines)
    # Labels come from the normative parameter data so docs cannot drift from the GUI.
    transformer_labels = next(p['labels'] for p in parameters if p['symbol'] == 'transformer')
    transformer_count = sum(1 for p in presets if p.get('transformer', 0))
    docs = ['# Instrument-Presets', '', '> Alle Werte sind eigene Ausgangspunkte, keine Hardwaremessungen.',
            '> Input bis zur gewünschten GR anpassen, Output anschließend pegelgleichen.',
            '> Ziel-GR meint stets die dynamische FET-Abschwächung im Wet-Pfad vor Mix; keine Pegelgarantie für den gespeicherten Inputwert.',
            '> Oversampling ist eine separate Qualitäts-/CPU-Auswahl (Default Off). JSFX-Selektor, importierte Factory-Bänke und LV2-Presets setzen Off.', '',
            '> Ab 0.4.0 sind 60s/80s/00s hörbar: warm/früh, ausgewogen, clean. Die Zuordnung ist eigene Klangabstimmung; keine historische Revision.', '',
            f'> Der Transformator ist eine Klangwahl und wandert daher mit dem Preset. Er steht bei',
            f'> {transformer_count} von {len(presets)} Presets auf einer Stufe und sonst auf `None`.',
            '', 'Prüfung und Änderungsbegründung: [EXTERN.md (Abschnitt Presetbewertung)](EXTERN.md).',
            'Ab 0.4.1: Attack in **21 Kick Weight** und **22 Snare Crack** korrigiert;',
            '**37 Piano Gentle 2:1** und **38 Stereo Bus Subtle 2:1** als zusätzliche Varianten.',
            'Die bisherigen Nummern bleiben erhalten. Input auf Ziel-GR einstellen und Output pegelgleichen.',
            '', '| Preset | Instrument | Input / Output dB | Attack / Release | Ratio | Mix / Colour % | Link | Transformator | Ziel-GR |',
            '|---|---|---|---|---|---|---|---|---|']
    # From the port definition, not a second hardcoded list: a new ratio step
    # has to be added in data/parameters.json only, or the preset table and the
    # GUI would silently disagree about what index 3 means.
    ratio_names = next(port['labels'] for port in parameters
                       if port.get('symbol') == 'ratio')
    assert len(ratio_names) == len(model['ratios']), 'ratio labels and gain law disagree'
    for p in presets:
        ratio = ratio_names[p['ratio']] if p['compression'] else 'Colour only'
        transformer=transformer_labels[p.get('transformer',0)]
        docs.append(f'| {p["name"]} | {p["instrument"]} | {p["input"]} / {p["output"]} | '
                    f'{p["attack"]} / {p["release"]} | {ratio} | {p["mix"]} / {p["colour"]} | '
                    f'{"On" if p["link"] else "Off"} | {transformer} | {p["target_gr"]} |')
    for p in presets:
        transformer=transformer_labels[p.get('transformer',0)]
        docs += ['', f'## {p["name"]}', '', p['note'], '',
                 f'Transformator: {transformer}.',
                 'Anregungen: ' + (', '.join(p['sources']) or 'Eigener musikalischer Startpunkt') + '.']
    files['docs/PRESETS.md'] = '\n'.join(docs) + '\n'
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
# read_text() without an encoding uses the locale encoding, which on Windows
#     is cp1252 and mangles the UTF-8 dashes in data/*.json.
    model = json.loads((ROOT/'data/model.json').read_text(encoding='utf-8'))
    parameters = json.loads((ROOT/'data/parameters.json').read_text(encoding='utf-8'))
    presets = json.loads((ROOT/'data/presets.json').read_text(encoding='utf-8'))
    transformers = json.loads((ROOT/model['transformer_bank']).read_text(encoding='utf-8'))
    labels = next(p['labels'] for p in parameters if p['symbol'] == 'transformer')
    if labels != ['None'] + list(transformers['profiles']):
        raise ValueError('Transformer port labels and runtime bank order disagree')
    files = dict(model_files(model), **metadata(parameters, presets, model), **jsfx_files(parameters, presets, model))
    files.update(transformer_files(transformers, number, eel_number))
    mismatch = []
    for path, text in files.items():
        destination = ROOT/path
        if args.check:
            if not destination.exists() or destination.read_text(encoding='utf-8') != text:
                mismatch.append(path)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            # Not Path.write_text(newline=...): that keyword only exists from
            # Python 3.10 on, and this generator has to run on the test machine,
            # which is on 3.9. Opening with newline='' writes the bytes as given
            # on every version, so the generated files keep LF everywhere.
            with destination.open('w', encoding='utf-8', newline='') as handle:
                handle.write(text)
    if mismatch:
        raise SystemExit('Generated files are stale: ' + ', '.join(mismatch))
    print(f'{"Verified" if args.check else "Generated"} {len(files)} files')


if __name__ == '__main__':
    main()
