#!/usr/bin/env python3
"""Generate shared constants, LV2 metadata, JSFX wrappers and preset data.

Only stdlib is required. --check compares without writing any files.
"""
import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PREFIX = "https://github.com/j4yj03/mod-1175-lv2#green-stripe-76-"
TTL_PREFIXES = '''@prefix lv2: <http://lv2plug.in/ns/lv2core#> .
@prefix doap: <http://usefulinc.com/ns/doap#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix units: <http://lv2plug.in/ns/extensions/units#> .
@prefix pprops: <http://lv2plug.in/ns/ext/port-props#> .
@prefix mod: <http://moddevices.com/ns/mod#> .
@prefix modgui: <http://moddevices.com/ns/modgui#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
'''


def number(value):
    return format(value, '.17g') if isinstance(value, float) else str(value)


def eel_number(value):
    # EEL2 does not accept C-style scientific literals in all hosts.
    text = number(value)
    if 'e' in text.lower():
        from decimal import Decimal
        text = format(Decimal(text), 'f')
    return text


def model_files(model):
    cpp = ['// Generated by tools/generate.py; edit data/model.json.',
           '#ifndef GREEN_STRIPE_MODEL_CONSTANTS_HPP',
           '#define GREEN_STRIPE_MODEL_CONSTANTS_HPP',
           'namespace greenstripe { namespace model {']
    eel = ['// Generated by tools/generate.py; SPDX-License-Identifier: MIT', '@init',
           'function gs_model_init() (']
    addresses = {'halfband_stage1': ('gs_coefs1', 0),
                 'halfband_stage2': ('gs_coefs2', 8),
                 'ratios': ('gs_ratios', 12), 'thresholds_dbfs': ('gs_thresholds', 17),
                 'knees_db': ('gs_knees', 22)}
    for key, value in model.items():
        if isinstance(value, str):
            continue
        if isinstance(value, list):
            cpp.append(f'static const double {key}[] = {{{", ".join(map(number, value))}}};')
            variable, address = addresses[key]
            eel.append(f'  {variable}={address};')
            eel.extend(f'  {variable}[{i}]={eel_number(x)};' for i, x in enumerate(value))
        else:
            kind = 'unsigned' if isinstance(value, int) else 'double'
            cpp.append(f'static const {kind} {key} = {number(value)};')
            eel.append(f'  gs_{key}={eel_number(value)};')
    cpp += ['} }', '#endif', '']
    eel += [');', '']
    return {'src/dsp/ModelConstants.hpp': '\n'.join(cpp),
            'jsfx/GreenStripe76-Model.jsfx-inc': '\n'.join(eel)}


def port(index, p):
    properties = []
    if p.get('labels'):
        properties += ['lv2:integer', 'lv2:enumeration']
    if p.get('toggle'):
        properties += ['lv2:integer', 'lv2:toggled']
    if p.get('connection_optional'):
        properties += ['lv2:connectionOptional']
    lines = [f'    [ a lv2:InputPort, lv2:ControlPort; lv2:index {index};',
             f'      lv2:symbol "{p["symbol"]}"; lv2:name "{p["name"]}";',
             f'      lv2:shortName "{p["short"]}"; lv2:default {number(p["default"])};',
             f'      lv2:minimum {number(p["min"])}; lv2:maximum {number(p["max"])};']
    if p.get('unit'):
        lines.append(f'      units:unit units:{p["unit"]};')
    if p.get('designation'):
        lines.append(f'      lv2:designation lv2:{p["designation"]};')
    if properties:
        lines.append('      lv2:portProperty ' + ', '.join(properties) + ';')
    for i, name in enumerate(p.get('labels', [])):
        lines.append(f'      lv2:scalePoint [ rdfs:label "{name}"; rdf:value {i} ];')
    steps = min(601, round((p['max'] - p['min']) / p['step']) + 1)
    lines.append(f'      pprops:rangeSteps {steps} ]')
    return '\n'.join(lines)


def metadata(parameters, presets, model):
    files = {}
    _, minor, micro = map(int, model['version'].split('.'))
    bundle = 'lv2/green-stripe-76.lv2/'
    manifest = [TTL_PREFIXES]
    gui = [TTL_PREFIXES]
    preset_text = [TTL_PREFIXES]
    for stereo in (False, True):
        variant = 'stereo' if stereo else 'mono'
        uri = PREFIX + variant
        manifest.append(f'<{uri}> a lv2:Plugin; lv2:binary <green-stripe-76.so>; '
                        f'rdfs:seeAlso <{variant}.ttl>, <modgui.ttl> .')
        ports = []
        audio = [('in_l', 'Input L', True), ('in_r', 'Input R', True),
                 ('out_l', 'Output L', False), ('out_r', 'Output R', False)] if stereo else [
                 ('in', 'Input', True), ('out', 'Output', False)]
        for i, (symbol, label, is_input) in enumerate(audio):
            ports.append(f'    [ a lv2:{"Input" if is_input else "Output"}Port, lv2:AudioPort; '
                         f'lv2:index {i}; lv2:symbol "{symbol}"; lv2:name "{label}" ]')
        controls = [p for p in parameters if stereo or not p.get('stereo_only')]
        existing_controls = [p for p in controls if not p.get('lv2_append')]
        appended_controls = [p for p in controls if p.get('lv2_append')]
        ports += [port(len(audio) + i, p) for i, p in enumerate(existing_controls)]
        latency_index = len(audio) + len(existing_controls)
        ports.append(f'    [ a lv2:OutputPort, lv2:ControlPort; lv2:index {latency_index}; '
                     'lv2:symbol "latency"; lv2:name "Nominal latency"; '
                     'lv2:designation lv2:latency; lv2:portProperty lv2:integer, pprops:notOnGUI; '
                      'units:unit units:frame; lv2:minimum 0; lv2:maximum 32; lv2:default 0 ]')
        ports += [port(latency_index + 1 + i, p) for i, p in enumerate(appended_controls)]
        files[bundle + variant + '.ttl'] = TTL_PREFIXES + f'''
<{uri}> a lv2:Plugin, lv2:CompressorPlugin;
    doap:name "Green Stripe 76 {variant.title()}";
    doap:license <https://opensource.org/license/mit>;
    doap:maintainer [ foaf:name "Green Stripe 76 contributors";
        foaf:homepage <https://github.com/j4yj03/mod-1175-lv2> ];
    mod:brand "GreenStripe"; mod:label "GS76 {variant.title()}";
    lv2:minorVersion {minor}; lv2:microVersion {micro};
    lv2:optionalFeature lv2:hardRTCapable;
    rdfs:comment "Independent FET feedback adaptation. Selectable Off/2x/4x oversampling, default Off, programme-dependent recovery, All Buttons and amplifier colour. No lookahead or brickwall guarantee. Nominal IIR latency is frequency dependent. Input/Output are digital dB gains. See project documentation.";
    lv2:port
''' + ',\n'.join(ports) + ' .\n'
        gui_ports = [p for p in controls if p['symbol'] != 'enabled']
        gui.append(f'''<{uri}> modgui:gui [
    modgui:resourcesDirectory <modgui>;
    modgui:iconTemplate <modgui/icon-{variant}.html>;
    modgui:stylesheet <modgui/green-stripe.css>;
    modgui:screenshot <modgui/screenshot-{variant}.png>;
    modgui:thumbnail <modgui/thumbnail-{variant}.png>;
    modgui:port
''' + ',\n'.join(f'    [ lv2:index {i}; lv2:symbol "{p["symbol"]}"; '
                      f'lv2:name "{p["name"]}" ]' for i, p in enumerate(gui_ports)) + ' ] .\n')
        for i, preset in enumerate(presets):
            preset_uri = PREFIX + f'preset-{variant}-{i+1:02d}'
            manifest.append(f'<{preset_uri}> a pset:Preset; lv2:appliesTo <{uri}>; '
                            f'rdfs:label "{preset["name"]}"; rdfs:seeAlso <presets.ttl> .')
            values = dict(preset, enabled=1, stereo_link=preset['link'], oversampling=0)
            preset_text.append(f'<{preset_uri}> a pset:Preset; lv2:appliesTo <{uri}>; '
                              f'rdfs:label "{preset["name"]}"; lv2:port\n' + ',\n'.join(
                                  f'    [ lv2:symbol "{p["symbol"]}"; pset:value {number(values[p["symbol"]])} ]'
                                  for p in controls) + ' .\n')
        files[bundle + f'modgui/icon-{variant}.html'] = gui_html(stereo)
    files[bundle + 'manifest.ttl'] = '\n'.join(manifest) + '\n'
    files[bundle + 'modgui.ttl'] = '\n'.join(gui) + '\n'
    files[bundle + 'presets.ttl'] = '\n'.join(preset_text) + '\n'
    return files


def gui_html(stereo):
    def knob(symbol, label):
        return (f'<div class="gs-control"><div class="gs-knob" mod-role="input-control-port" mod-port-symbol="{symbol}" mod-widget-rotation="270"></div>'
                f'<label>{label}</label><span mod-role="input-control-value" mod-port-symbol="{symbol}"></span></div>')
    def select(symbol, label, options):
        return (f'<div class="gs-sel"><label>{label}</label><select mod-role="input-control-port" mod-port-symbol="{symbol}" mod-widget="select">'
                + ''.join(f'<option value="{i}">{text}</option>' for i, text in enumerate(options)) + '</select></div>')
    inputs = ''.join(f'<div class="gs-jack" mod-role="input-audio-port" mod-port-symbol="{x}"></div>' for x in (['in_l','in_r'] if stereo else ['in']))
    outputs = ''.join(f'<div class="gs-jack" mod-role="output-audio-port" mod-port-symbol="{x}"></div>' for x in (['out_l','out_r'] if stereo else ['out']))
    return f'''<!-- Generated. JSFX-console styling; no GR/level meters in MOD GUI. -->
<div class="gs76{{{{{{cns}}}}}}" mod-role="drag-handle">
<div class="mod-drag-handle"></div>
<div class="gs-groups">
<div class="gs-group"><b>GAIN</b>{knob('input','INPUT')}{knob('output','OUTPUT')}</div>
<div class="gs-group"><b>TIME</b>{knob('attack','ATTACK')}{knob('release','RELEASE')}</div>
<div class="gs-group gs-group-flags"><b>ENGINE</b>{select('ratio','RATIO',['4:1','8:1','12:1','20:1','ALL'])}{select('compression','MODE',['COLOUR ONLY','COMP ON'])}{select('stereo_link','LINK',['DUAL MONO','LINK']) if stereo else ''}</div>
<div class="gs-group gs-group-wide"><b>COLOUR</b><div class="gs-pair">{knob('mix','MIX')}{knob('colour','COLOUR')}</div>{select('oversampling','OVERSAMPLING',['OS OFF','OS 2x','OS 4x'])}</div>
</div>
<footer>
<div class="gs-title"><b>GREEN STRIPE 76</b><small>FET FEEDBACK · INDEPENDENT 1176-INSPIRED GRAY-BOX · {'STEREO' if stereo else 'MONO'}</small></div>
<div class="gs-bypass" mod-role="bypass">BYPASS</div><span class="gs-light" mod-role="bypass-light"></span>
</footer>
<div class="gs-inputs">{inputs}</div><div class="gs-outputs">{outputs}</div>
</div>
'''
def jsfx_files(parameters, presets, model):
    files = {}
    preset_eel = ['// Generated instrument starting points; not hardware measurements.', '@init',
                  'function gs_apply_preset(which) (']
    for i, p in enumerate(presets):
        preset_eel.append(f'  which=={i+1} ? (')
        values = [p[x] for x in ('input','output','attack','release','ratio','mix','colour','compression')]
        values += [1, p['link']]
        preset_eel += [f'    slider{j+1}={number(x)};' for j, x in enumerate(values)]
        preset_eel.append('  );')
    preset_eel += ['  sliderchange(1023);', ');', '']
    files['jsfx/GreenStripe76-Presets.jsfx-inc'] = '\n'.join(preset_eel)
    for stereo in (False, True):
        variant = 'Stereo' if stereo else 'Mono'
        rpl = [f'<REAPER_PRESET_LIBRARY "Green Stripe 76 {variant}"']
        for preset in presets:
            values = [preset[x] for x in ('input','output','attack','release','ratio','mix','colour','compression')]
            values += [1,preset['link'],0,0]
            state = ' '.join([number(x) for x in values] + ['-']*(64-len(values)))
            payload = base64.b64encode((state + ' "' + preset['name'] + '"\x00').encode('utf-8')).decode('ascii')
            rpl += [f'  <PRESET "{preset["name"]}"', '    '+payload, '  >']
        rpl += ['>', '']
        files[f'jsfx/GreenStripe76-{variant}.rpl'] = '\n'.join(rpl)
        lines = [f'desc:Green Stripe 76 {variant}', 'author:Green Stripe 76 contributors',
                 f'version:{model["version"]}', 'tags:dynamics compressor limiter fet',
                 '// SPDX-License-Identifier: MIT',
                 'options:maxmem=8192 prealloc=8192 gfx_hz=30',
                 'import GreenStripe76-Core.jsfx-inc',
                 'import GreenStripe76-Presets.jsfx-inc',
                 'import GreenStripe76-UI.jsfx-inc']
        for i, p in enumerate(parameters):
            label = p['name']
            if p.get('unit') == 'db': label += ' (dB)'
            if p.get('unit') == 'pc': label += ' (%)'
            if not stereo and p.get('stereo_only'): label = '-' + label
            labels = '{' + ','.join(p['labels']) + '}' if p.get('labels') else '{Off,On}' if p.get('toggle') else ''
            slider_index = p.get('jsfx_slider', i + 1)
            lines.append(f'slider{slider_index}:{p["default"]}<{p["min"]},{p["max"]},{p["step"]}{labels}>{label}')
        names = 'Custom,' + ','.join(p['name'] for p in presets)
        lines.append(f'slider11:0<0,{len(presets)},1{{{names}}}>Instrument preset')
        lines += ['in_pin:Input L', 'in_pin:Input R', 'out_pin:Output L', 'out_pin:Output R',
                  '', '@init', 'ext_nodenorm=1; ext_tail_size=-1; ext_gr_meter=0;',
                  'gfx_ext_retina=1;', f'gs_stereo={1 if stereo else 0};',
                  'gs_engine.gs_reset(gs_stereo); gs_rate=srate;',
                  'gs_inL.gs_meter_init(); gs_inR.gs_meter_init();',
                  'gs_outL.gs_meter_init(); gs_outR.gs_meter_init();',
                  'gs_grL=gs_grR=gs_peakGR=0; gs_last_preset=slider11; gs_have_controls=0;',
                  'gs_meter_decay=exp(-1/(0.35*max(8000,srate)));',
                  'gs_meter_rms=1-exp(-1/(0.3*max(8000,srate)));',
                  '', '@slider',
                  'slider11!=gs_last_preset ? (slider11>0 ? gs_apply_preset(slider11); gs_last_preset=slider11;) : (',
                  '  gs_have_controls && (slider1!=gs_prev1 || slider2!=gs_prev2 || slider3!=gs_prev3 || slider4!=gs_prev4 || slider5!=gs_prev5 || slider6!=gs_prev6 || slider7!=gs_prev7 || slider8!=gs_prev8 || slider9!=gs_prev9 || slider10!=gs_prev10) ? (',
                  '    slider11=0; gs_last_preset=0; sliderchange(slider11);',
                  '  );', ');',
                  'gs_prev1=slider1; gs_prev2=slider2; gs_prev3=slider3; gs_prev4=slider4; gs_prev5=slider5;',
                  'gs_prev6=slider6; gs_prev7=slider7; gs_prev8=slider8; gs_prev9=slider9; gs_prev10=slider10; gs_have_controls=1;',
                  'gs_engine.gs_set(slider1,slider2,slider3,slider4,slider5,slider6,slider7,slider8,slider9,slider10,slider12);',
                  '', '@block', 'srate!=gs_rate ? (',
                  '  gs_engine.gs_reset(gs_stereo); gs_rate=srate;',
                  '  gs_meter_decay=exp(-1/(0.35*max(8000,srate)));',
                  '  gs_meter_rms=1-exp(-1/(0.3*max(8000,srate)));', ');',
                  'gs_engine.gs_set(slider1,slider2,slider3,slider4,slider5,slider6,slider7,slider8,slider9,slider10,slider12);',
                  'pdc_delay=gs_engine.gs_latency(); pdc_bot_ch=0; pdc_top_ch=2;',
                  'atomic_set(gs_ui_os_active,gs_engine.os_active);',
                  'ext_gr_meter=gs_peakGR; gs_peakGR=0;',
                  'atomic_set(gs_audio_time,time_precise());',
                  'atomic_set(gs_ui_inL,gs_gain_db(gs_inL.peak)); atomic_set(gs_ui_inR,gs_gain_db(gs_stereo ? gs_inR.peak : gs_inL.peak));',
                  'atomic_set(gs_ui_outL,gs_gain_db(gs_outL.peak)); atomic_set(gs_ui_outR,gs_gain_db(gs_stereo ? gs_outR.peak : gs_outL.peak));',
                  'atomic_set(gs_ui_inRmsL,gs_gain_db(sqrt(max(0,gs_inL.rms))));',
                  'atomic_set(gs_ui_inRmsR,gs_gain_db(sqrt(max(0,gs_stereo ? gs_inR.rms : gs_inL.rms))));',
                  'atomic_set(gs_ui_rmsL,gs_gain_db(sqrt(max(0,gs_outL.rms))));',
                  'atomic_set(gs_ui_rmsR,gs_gain_db(sqrt(max(0,gs_stereo ? gs_outR.rms : gs_outL.rms))));',
                  'atomic_set(gs_ui_holdL,gs_gain_db(gs_outL.hold)); atomic_set(gs_ui_holdR,gs_gain_db(gs_stereo ? gs_outR.hold : gs_outL.hold));',
                  'atomic_set(gs_ui_inHoldL,gs_gain_db(gs_inL.hold)); atomic_set(gs_ui_inHoldR,gs_gain_db(gs_stereo ? gs_inR.hold : gs_inL.hold));',
                  'atomic_set(gs_ui_inClipL,gs_inL.clip); atomic_set(gs_ui_inClipR,gs_stereo ? gs_inR.clip : gs_inL.clip);',
                  'atomic_set(gs_ui_grL,gs_grL); atomic_set(gs_ui_grR,gs_grR);',
                  'atomic_set(gs_ui_clipL,gs_outL.clip); atomic_set(gs_ui_clipR,gs_stereo ? gs_outR.clip : gs_outL.clip);',
                  '', '@sample',
                  'gs_rawL=gs_bound(gs_finite(spl0,0),-256,256);',
                  'gs_rawR=gs_bound(gs_finite(spl1,0),-256,256);',
                  'gs_stereo ? gs_engine.gs_process(gs_rawL,gs_rawR) : gs_engine.gs_process(gs_rawL,gs_rawL);',
                  'spl0=gs_engine.outL; spl1=gs_engine.outR;',
                  'gs_inL.gs_meter_sample(gs_rawL); gs_outL.gs_meter_sample(spl0);',
                  'gs_stereo ? (gs_inR.gs_meter_sample(gs_rawR); gs_outR.gs_meter_sample(spl1););',
                  'gs_peakGR=min(gs_peakGR,min(gs_engine.grL,gs_engine.grR));',
                  'gs_grL=max(-gs_engine.grL,gs_grL*gs_meter_decay);',
                  'gs_grR=max(-gs_engine.grR,gs_grR*gs_meter_decay);',
                  '', '@gfx 820 380', 'gs_draw_ui(gs_stereo);', '']
        files[f'jsfx/GreenStripe76-{variant}.jsfx'] = '\n'.join(lines)
    docs = ['# Instrument-Presets', '', '> Alle Werte sind eigene Ausgangspunkte, keine Hardwaremessungen.',
            '> Input bis zur gewünschten GR anpassen, Output anschließend pegelgleichen.',
            '> Oversampling ist eine separate Qualitäts-/CPU-Auswahl (Default Off). Der eingebaute JSFX-Selektor lässt sie unverändert; importierte Factory-Bänke und LV2-Presets setzen Off.', '',
            '| Preset | Instrument | Input / Output dB | Attack / Release | Ratio | Mix / Colour % | Link | Ziel-GR |',
            '|---|---|---|---|---|---|---|---|']
    ratio_names = ['4:1','8:1','12:1','20:1','All']
    for p in presets:
        ratio = ratio_names[p['ratio']] if p['compression'] else 'Colour only'
        docs.append(f'| {p["name"]} | {p["instrument"]} | {p["input"]} / {p["output"]} | '
                    f'{p["attack"]} / {p["release"]} | {ratio} | {p["mix"]} / {p["colour"]} | '
                    f'{"On" if p["link"] else "Off"} | {p["target_gr"]} |')
    for p in presets:
        docs += ['', f'## {p["name"]}', '', p['note'], '',
                 'Anregungen: ' + (', '.join(p['sources']) or 'Eigener musikalischer Startpunkt') + '.']
    files['docs/PRESETS.md'] = '\n'.join(docs) + '\n'
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    model = json.loads((ROOT/'data/model.json').read_text())
    parameters = json.loads((ROOT/'data/parameters.json').read_text())
    presets = json.loads((ROOT/'data/presets.json').read_text())
    files = dict(model_files(model), **metadata(parameters, presets, model), **jsfx_files(parameters, presets, model))
    mismatch = []
    for path, text in files.items():
        destination = ROOT/path
        if args.check:
            if not destination.exists() or destination.read_text(encoding='utf-8') != text:
                mismatch.append(path)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(text, encoding='utf-8', newline='\n')
    if mismatch:
        raise SystemExit('Generated files are stale: ' + ', '.join(mismatch))
    print(f'{"Verified" if args.check else "Generated"} {len(files)} files')


if __name__ == '__main__':
    main()
