#!/usr/bin/env python3
"""Validated, versioned transformer bank and C++/EEL2 constants (stdlib only)."""
import argparse
import copy
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIELDS = ('lm_h', 'flux_scale_vs', 'hysteresis_stiffness_a_per_vs',
          'hysteresis_slope', 'relax_l_h', 'relax_frequency_hz',
          'core_conductance_s', 'hf_frequency_hz', 'hf_q',
          'source_resistance_ohm', 'primary_resistance_ohm',
          'secondary_resistance_ohm', 'load_resistance_ohm',
          'hysteresis_enabled', 'family', 'exponent', 'saturation_strength',
          'high_field_l_ratio', 'nonlinear_series_resistance_ohm',
          'source_volts_per_fs', 'fixed_output_normalization')
THRESHOLDS = [0.00002, 0.00005, 0.0001, 0.0002, 0.0005, 0.001, 0.002,
              0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5]


def validate(bank):
    if bank['schema_version'] != 1 or not isinstance(bank['revision'],str) or not bank['revision'].strip():
        raise ValueError('Unsupported schema or missing model revision')
    for key in ('source_sha256','source_fit_sha256'):
        value=bank.get(key,'')
        if not isinstance(value,str) or len(value)!=64 or any(c not in '0123456789abcdef' for c in value):
            raise ValueError(f'Missing/invalid provenance: {key}')
    if list(bank['profiles']) != ['60s', '80s', '00s', 'Symmetric']:
        raise ValueError('Stable profile order must be 60s, 80s, 00s, Symmetric')
    if bank['stop_thresholds_vs'] != THRESHOLDS:
        raise ValueError('This runtime supports the documented 14 stop thresholds')
    for name, p in bank['profiles'].items():
        if set(p) != set(FIELDS):
            raise ValueError(f'{name}: incomplete/unknown model parameters')
        for key, value in p.items():
            if not isinstance(value, (int, float)) or not math.isfinite(value):
                raise ValueError(f'{name}/{key}: must be finite numeric')
        limits = {
            'lm_h': (1, 100000), 'flux_scale_vs': (.0001, 10),
            'hysteresis_stiffness_a_per_vs': (0, .1), 'hysteresis_slope': (-1, 1),
            'relax_l_h': (1, 100000), 'relax_frequency_hz': (.001, 1000),
            'core_conductance_s': (0, .01), 'hf_frequency_hz': (20000, 500000),
            'hf_q': (.51, 1), 'source_resistance_ohm': (0, 100000),
            'primary_resistance_ohm': (1, 100000), 'secondary_resistance_ohm': (0, 100000),
            'load_resistance_ohm': (1, 1000000), 'saturation_strength': (0, 2),
            'high_field_l_ratio': (0, .1), 'source_volts_per_fs': (.01, 100),
            'fixed_output_normalization': (.01, 10)}
        for key, (low, high) in limits.items():
            if not low <= p[key] <= high:
                raise ValueError(f'{name}/{key}: outside [{low}, {high}]')
        if p['family'] not in (0, 1) or p['exponent'] not in (1, 3, 5, 7):
            raise ValueError(f'{name}: unsupported magnetization law')
        if p['family'] == 1 and (p['exponent'] != 1 or p['high_field_l_ratio'] < .00001):
            raise ValueError(f'{name}: Frohlich requires finite high-field continuation')
        if p['family'] == 0 and p['exponent'] < 3:
            raise ValueError(f'{name}: polynomial exponent must be >=3')
        if p['hysteresis_enabled'] not in (0, 1) or p['nonlinear_series_resistance_ohm'] != 0:
            raise ValueError(f'{name}: unsupported memory/series branch')
    return bank


def generated(bank, number, eel_number):
    validate(bank)
    profiles = list(bank['profiles'].values())
    provenance = '// Bank revision: '+bank['revision']+'; source SHA256: '+bank['source_sha256']
    cpp = ['// Generated by tools/generate.py; edit data/transformers.json.', provenance,
           '#ifndef GREEN_STRIPE_TRANSFORMER_MODELS_HPP', '#define GREEN_STRIPE_TRANSFORMER_MODELS_HPP',
           'namespace greenstripe { namespace transformer_model {',
           'struct Profile {']
    cpp += [f'    double {key};' for key in FIELDS]
    cpp += ['};', 'static const Profile profiles[] = {']
    cpp += ['    {' + ', '.join(number(p[k]) for k in FIELDS) + '},' for p in profiles]
    cpp += ['};', 'static const double thresholds[] = {' + ', '.join(map(number, THRESHOLDS)) + '};',
            '} }', '#endif', '']
    eel = ['// Generated by tools/generate.py; edit data/transformers.json.', provenance, '@init',
           'function gs_xf_model(which dest) (']
    for i, p in enumerate(profiles):
        eel += [f'  which==={i+1} ? (']
        eel += [f'    dest[{j}]={eel_number(p[k])};' for j, k in enumerate(FIELDS)]
        eel += ['  );']
    eel += [');', 'function gs_xf_thresholds(dest) (']
    eel += [f'  dest[{j}]={eel_number(x)};' for j, x in enumerate(THRESHOLDS)]
    eel += [');', '']
    return {'src/dsp/TransformerModels.hpp': '\n'.join(cpp),
            'jsfx/GreenStripe76-Transformers.jsfx-inc': '\n'.join(eel)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--import-profiles', type=Path, required=True)
    parser.add_argument('--revision', required=True)
    parser.add_argument('--output', type=Path, default=ROOT/'data/transformers.json')
    args = parser.parse_args()
    raw = args.import_profiles.read_bytes()
    source = json.loads(raw)
    profiles = {}
    for name in ('60s', '80s', '00s'):
        p = source['profiles'][name]
        profiles[name] = dict(p['parameters'], source_volts_per_fs=p['source_volts_per_fs'],
                             fixed_output_normalization=p['fixed_output_normalization'])
    reference = copy.deepcopy(profiles['00s'])
    reference.update(family=0, exponent=3, saturation_strength=0,
                     hysteresis_enabled=0, high_field_l_ratio=0)
    profiles['Symmetric'] = reference
    bank = validate(dict(schema_version=1, revision=args.revision,
                         source_sha256=hashlib.sha256(raw).hexdigest(),
                         source_fit_sha256=source['fit_sha256'],
                         status='Own gray-box profiles; partial datasheet fit, not hardware calibration',
                         stop_thresholds_vs=THRESHOLDS, profiles=profiles))
    with args.output.open('w', encoding='utf-8', newline='') as stream:
        stream.write(json.dumps(bank, indent=2, ensure_ascii=False)+'\n')
    print(f'Validated transformer bank: {args.output}; run tools/generate.py and acceptance tests')


if __name__ == '__main__':
    main()
